import { SkillsList } from '@free-resume/models-types';

export const skills: SkillsList = {
  Backend: [
    'Java',
    'Node.js',
    'Spring',
    'PostgreSQL',
    'Express.js',
    'Django',
    'Ruby on Rails',
    'Flask',
    'Go',
    'Kotlin',
    'C#',
    'ASP.NET',
    'GraphQL',
    'PHP',
    'Laravel',
    'Hibernate',
    'Rust',
    'Scala',
    'Elixir',
    'Perl',
  ],
  Frontend: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Angular',
    'Vue.js',
    'TypeScript',
    'Sass',
    'Bootstrap',
    'Tailwind CSS',
    'jQuery',
    'Redux',
    'Next.js',
    'Nuxt.js',
    'Ember.js',
    'Svelte',
    'Webpack',
    'Gulp',
    'Babel',
    'LitElement',
  ],
  'Data Science': [
    'Python',
    'TensorFlow',
    'Keras',
    'PyTorch',
    'Scikit-Learn',
    'Pandas',
    'NumPy',
    'R',
    'Matplotlib',
    'Seaborn',
    'SQL',
    'Tableau',
    'Power BI',
    'Apache Spark',
    'Hadoop',
    'Jupyter',
    'D3.js',
    'ggplot2',
    'NLTK',
    'Data Wrangling',
  ],
  DevOps: [
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Git',
    'Ansible',
    'Terraform',
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'CI/CD',
    'Puppet',
    'Chef',
    'Nagios',
    'Prometheus',
    'Grafana',
    'Travis CI',
    'CircleCI',
    'Bamboo',
    'Splunk',
    'ELK Stack',
  ],
  Databases: [
    'MySQL',
    'MongoDB',
    'PostgreSQL',
    'Oracle',
    'SQL Server',
    'SQLite',
    'Cassandra',
    'Redis',
    'Elasticsearch',
    'Firebase',
    'MariaDB',
    'DynamoDB',
    'CouchDB',
    'Neo4j',
    'HBase',
    'Memcached',
    'Realm',
    'CockroachDB',
    'ClickHouse',
    'FaunaDB',
  ],
  'Mobile Development': [
    'Swift',
    'Kotlin',
    'React Native',
    'Flutter',
    'Java',
    'Objective-C',
    'Ionic',
    'Xamarin',
    'Cordova',
    'Android SDK',
    'iOS SDK',
    'Dart',
    'Unity',
    'PhoneGap',
    'Firebase',
    'Appcelerator',
    'Sencha Touch',
    'Corona SDK',
    'ARKit',
    'ARCore',
  ],
  'Cloud Computing': [
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'IBM Cloud',
    'Heroku',
    'Oracle Cloud',
    'Cloud Foundry',
    'OpenStack',
    'Alibaba Cloud',
    'Salesforce',
    'VMware',
    'Red Hat OpenShift',
    'DigitalOcean',
    'Linode',
    'Rackspace',
    'Cloudflare',
    'Netlify',
    'Vercel',
    'Terraform',
    'Serverless',
  ],
  Cybersecurity: [
    'Penetration Testing',
    'Network Security',
    'Cryptography',
    'Ethical Hacking',
    'Incident Response',
    'SIEM',
    'IDS/IPS',
    'Firewalls',
    'Risk Management',
    'Compliance',
    'Forensics',
    'Malware Analysis',
    'Vulnerability Assessment',
    'Security Auditing',
    'Zero Trust',
    'IAM (Identity and Access Management)',
    'PKI (Public Key Infrastructure)',
    'SOC (Security Operations Center)',
    'Data Loss Prevention',
    'Endpoint Security',
  ],
  Networking: [
    'TCP/IP',
    'DNS',
    'HTTP/HTTPS',
    'Load Balancing',
    'VPN',
    'Proxy Servers',
    'Routing Protocols',
    'Network Monitoring',
    'Wi-Fi',
    'LAN/WAN',
    'IPv6',
    'MPLS',
    'BGP',
    'OSPF',
    'NAT',
    'VoIP',
    'SDN (Software-Defined Networking)',
    'QoS (Quality of Service)',
    'Cisco IOS',
    'Juniper',
  ],
  'AI and Machine Learning': [
    'Machine Learning',
    'Deep Learning',
    'Natural Language Processing',
    'Computer Vision',
    'Reinforcement Learning',
    'Artificial Intelligence',
    'Neural Networks',
    'Big Data',
    'Data Mining',
    'Predictive Analytics',
    'OpenCV',
    'Spacy',
    'Gensim',
    'XGBoost',
    'LightGBM',
    'H2O.ai',
    'RapidMiner',
    'AutoML',
    'Feature Engineering',
    'Model Deployment',
  ],
  'Software Development': [
    'Agile',
    'Scrum',
    'Kanban',
    'Test-Driven Development',
    'Version Control',
    'Continuous Integration',
    'Continuous Deployment',
    'Software Testing',
    'Code Review',
    'Refactoring',
    'Pair Programming',
    'Design Patterns',
    'Microservices',
    'SOLID Principles',
    'Domain-Driven Design',
    'Behavior-Driven Development',
    'Extreme Programming',
    'UML',
    'RESTful APIs',
    'GraphQL',
  ],
};

export const languages: string[] = [
  'Mandarin Chinese',
  'Spanish',
  'English',
  'Hindi',
  'Arabic',
  'Portuguese',
  'Bengali',
  'Russian',
  'Japanese',
  'Punjabi',
  'German',
  'Javanese',
  'Wu Chinese',
  'Korean',
  'French',
];
